version: '3.7'
# version

services:
  app:
    build: 
      context: .
    container_name: url_shortner
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true