# Generated by Django 4.2.3 on 2023-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_url_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortened_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
